### ISSUE TITLE
Accept pull request for formatting/conventions?

### ISSUE THREAD

**Issue by patcon** [varnish/cookbooks#2]
Is this still maintained? Just wondering whether you'd accept a pull request for formatting-related things:
http://acrmp.github.com/foodcritic/
- cache dir
- strings for accessing node attributes
- using apt_repository LWRP to add gpg key and repo

mostly keeping it the same though.

Also any reason some of this couldn't be pushed to the opscode repo? I'm a registered contributor whose pull requests can be accepted, if that's the reason. Please let me know :)

**Comment by patcon** [comment]
Is this repo abandoned?

Posting this for posterity. https://github.com/opscode-cookbooks/varnish/network

Would be nice if someone could convert this into a real fork so that it's features are part of that "conversation"

Cheers.

**Comment by adrianmoisey** [comment]
This looks dead :(
https://github.com/rackspace-cookbooks/varnish looks like the cookbook to use now

**Comment by lkarsten** [comment]
Hi.

We really don't have any active community members that run chef any more, so this has been unmaintained for a while.

Thanks for providing links to the updated version.

-Lasse
(Varnish release manager hat on)
